


synctaub:
	rsync -a -r -u -E -z --progress -t --stats . hwang154@taub.campuscluster.illinois.edu:/home/hwang154/workspace/cs554.project/src
	
syncews:
	rsync -a -r -u -E -z --progress -t --stats . hwang154@remlnx.ews.illinois.edu:/home/hwang154/workspace/cs554.project/src